server:
  #  ${port:8085} 没有port参数，使用8085端口，有port参数则使用port参数指定的端口，使用8086端口的支付服务。 -Dport=8086
  port: ${port:8085}

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

# 启用熔断器，LoadBalancer 抛出的异常也会进入 Feign fallback，否则Feign（负载均衡错误，例如：服务关闭、连不上不会进入 fallback） 不经过 Sentinel
feign:
  sentinel:
    enabled: true